version: "3"
services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql6
    command: mysqld 
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "33060:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret1
      - MYSQL_USER=demo
      - MYSQL_DATABASE=demo
      - MYSQL_PASSWORD=secret2

  maven-app:
    container_name: ex3-maven-app-1
    image: maven-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - "mysql"
    command: [ "./mvnw", "spring-boot:run" ]
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/demo
      - spring.datasource.username=demo
      - spring.datasource.password=secret2
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=update

    

volumes:
  mysql-data:
    driver: local
