# syntax=docker/dockerfile:1
FROM node:12-alpine
RUN apk add --no-cache python g++ make
WORKDIR
Learn more about the "WORKDIR" Dockerfile command.
 /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]